{
  "formatVersion": "1.1",
  "component": {
    "group": "soda",
    "module": "hiyPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "prhhs5mmhnd4bekzz3fd2lw4iu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hiyPlugin-unspecified.jar",
          "url": "hiyPlugin-unspecified.jar",
          "size": 1708,
          "sha512": "6ae788d2f07f6ed212238e33009af5029a1a6502d4547ffe3732ac80a5e962c08fd88034e61f982af4d4e9ed5be3d5d3e93acd08ad7b4069562bb915aa81c204",
          "sha256": "27fa96a26b5e5e1aed8eb20d9d5e0da9afa50c3a60ecab423f0ae1dac098827d",
          "sha1": "f536b2cc0d39a247b6bfa4995b5d414f9faf2844",
          "md5": "403ccc26e0af9cbe128b8e1fb0e5cf88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hiyPlugin-unspecified.jar",
          "url": "hiyPlugin-unspecified.jar",
          "size": 1708,
          "sha512": "6ae788d2f07f6ed212238e33009af5029a1a6502d4547ffe3732ac80a5e962c08fd88034e61f982af4d4e9ed5be3d5d3e93acd08ad7b4069562bb915aa81c204",
          "sha256": "27fa96a26b5e5e1aed8eb20d9d5e0da9afa50c3a60ecab423f0ae1dac098827d",
          "sha1": "f536b2cc0d39a247b6bfa4995b5d414f9faf2844",
          "md5": "403ccc26e0af9cbe128b8e1fb0e5cf88"
        }
      ]
    }
  ]
}
